# Generated by Django 4.0.2 on 2022-02-28 18:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
